version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: toka_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: toka_db
    ports:
      - "5433:5432"

  mongo:
    image: mongo:7
    container_name: toka_mongo
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    container_name: toka_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: toka_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  qdrant:
    image: qdrant/qdrant
    container_name: toka_qdrant
    ports:
      - "6333:6333"
